export { default as logoImage } from './logo.png'
export { default as noGameImage } from './games/default.png'
export { default as ticTacToeImage } from './games/tictactoe.png'
export { default as clobberImage } from './games/clobber.png'
export { default as moreGamesImage } from './more-games.png'
export { default as pfpImage } from './pfp.png'
export { default as profilePictureImage } from './profile-picture.png'

// Avatars
export { default as avatar1 } from './avatar/1.png'
export { default as avatar2 } from './avatar/2.png'
export { default as avatar3 } from './avatar/3.png'
export { default as avatar4 } from './avatar/4.png'
export { default as avatar5 } from './avatar/5.png'
export { default as avatar6 } from './avatar/6.png'
export { default as avatar7 } from './avatar/7.png'
export { default as avatar8 } from './avatar/8.png'
export { default as avatar9 } from './avatar/9.png'
export { default as avatar10 } from './avatar/10.png'
export { default as avatar11 } from './avatar/11.png'
export { default as avatar12 } from './avatar/12.png'
export { default as avatar13 } from './avatar/13.png'
export { default as avatar14 } from './avatar/14.png'
export { default as avatar15 } from './avatar/15.png'
export { default as avatar16 } from './avatar/16.png'
